var nav = React.createElement(   "nav",   { className: "menu" }, 
    React.createElement(     "ul",     null,    
	React.createElement(       "li",       null,     
	React.createElement(         "a",         { href: "#" },         "Home"       )     ),    
	React.createElement(       "li",       null,      
	React.createElement(         "a",         { href: "#" },         "About"       )     )   ) );